#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
BASE=$(git merge-base @ "$UPSTREAM")

if [ -f .git/MERGE_HEAD ]; then
	echo "Merge in progress";
	exit
else
	if [ $LOCAL = $REMOTE ]; then
		echo "Up-to-date"
		pnpm format
		exit
	elif [ $LOCAL = $BASE ]; then
		echo "Need to pull"
	elif [ $REMOTE = $BASE ]; then
		echo "Need to push"
	else
		echo "Diverged"
	fi
		exit 1
fi